import { useEffect,useRef,useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import Sidebar from '../components/Sidebar';import Header from '../components/Header';import InstitutionsFilters from '../components/InstitutionsFilters';import InstitutionsTable from '../components/InstitutionsTable';import { api } from '../api';
export default function InstitutionsPage(){
 const [sp]=useSearchParams();const [filters,setFilters]=useState({q:sp.get('q')||'',region:'',manager_id:'',status:'',direction_id:'',product_id:''});const [catalogs,setCatalogs]=useState({});const [data,setData]=useState({items:[],total:0,page:1,size:20});const [loading,setLoading]=useState(true);const [catalog,setCatalog]=useState('institutions');const fileRef=useRef();
 const load=async(page=1,override=filters)=>{setLoading(true);const qs=new URLSearchParams({page,size:20,...Object.fromEntries(Object.entries(override).filter(([,v])=>v))});try{setData(await api(`/api/institutions?${qs}`))}finally{setLoading(false)}};
 useEffect(()=>{api('/api/catalogs').then(setCatalogs);load(1)},[]);
 useEffect(()=>{const q=sp.get('q')||'';if(q!==filters.q){const f={...filters,q};setFilters(f);load(1,f)}},[sp]);
 const importFile=async e=>{const f=e.target.files?.[0];if(!f)return;const fd=new FormData();fd.append('file',f);try{const r=await api(`/api/import/${catalog}`,{method:'POST',body:fd});alert(`Импорт ${r.catalog}: создано ${r.created}, обновлено ${r.updated}`);api('/api/catalogs').then(setCatalogs);load(1)}catch(err){alert(err.message)}e.target.value=''};
 return <div className="min-h-screen flex bg-gray-50"><Sidebar activeItem="Вузы"/><div className="flex-1 flex flex-col min-w-0"><Header/><main className="flex-1 p-4 md:p-6 overflow-auto"><div className="flex items-start justify-between mb-6 flex-wrap gap-3"><div><h1 className="text-2xl font-bold text-gray-800">Вузы</h1><p className="text-sm text-gray-500 mt-1">Каталоги и текущие взаимодействия</p></div><div className="flex gap-2"><select value={catalog} onChange={e=>setCatalog(e.target.value)} className="px-3 py-2 border rounded-lg text-sm"><option value="institutions">Вузы</option><option value="directions">ИТ-направления</option><option value="products">ИТ-продукты</option><option value="managers">Ответственные</option></select><input ref={fileRef} type="file" accept=".xls,.xlsx" className="hidden" onChange={importFile}/><button onClick={()=>fileRef.current?.click()} className="px-4 py-2.5 rounded-lg bg-white border text-sm font-medium">Импорт XLS/XLSX</button></div></div><InstitutionsFilters filters={filters} setFilters={setFilters} catalogs={catalogs} onSearch={()=>load(1)}/>{loading?<div className="p-8 text-gray-500">Загрузка...</div>:<InstitutionsTable rows={data.items} total={data.total} page={data.page} size={data.size} onPage={load}/>}</main></div></div>
}
